### ISSUE TITLE
How can I remap a keybind to a stylus button?

### ISSUE THREAD

**Issue by Settordici** [linuxwacom/gsetwacom#19]
Hi, I want to remap a keybind to the stylus of my Wacom Intuos S but I'm not sure if I'm typing everything right.
I'm attaching a screenshot of my command and the output

![image](https://github.com/user-attachments/assets/7c8329f0-ed07-4d5c-bab2-6303b68ffc52)

**Comment by whot** [comment]
That feature was added for the upcoming GNOME47 - are you on that?

**Comment by Settordici** [comment]
Oh I'm on 46, you are right. Is it mentioned in the readme? I didn't find anything about it

**Comment by whot** [comment]
It's not mentioned anywhere I think - I'd happily merge a PR for that though.

Problem is that most of the relocatable bindings are not detectable at all, e.g. you can set a keybinding for button that doesn't exist on a stylus you don't have. So I didn't really bother that much with error checking.
